In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://www.espncricinfo.com/records/trophy/batting-list-hundreds/indian-premier-league-117"

In [3]:
response = requests.get(url)

In [4]:
import numpy as np
import pandas as pd
import re

In [5]:
columns = []
rows = []
if response.status_code == 200:
    
    soup = BeautifulSoup(response.text, 'html.parser')
    
    table = soup.find('table')
    
    if table:
        
        for row in table.find_all('tr'):
           
            cells = row.find_all('th')  
            for cell in cells:
                columns.append(cell.get_text())
            
        for row in table.find_all('tr'):
            
            cells = row.find_all("td")
            for cell in cells:
                 rows.append(cell.text)   
    else:
        print('No table found on the webpage.')

else:
    print(f'Failed to retrieve the webpage. Status code: {response.status_code}')

In [11]:
columns = rows[0:12]

In [12]:
numArray = np.array(rows[12:])

In [14]:
frame = []

In [15]:
for i in range(len(columns),len(numArray),len(columns)):
    frame.append(numArray[i-len(columns):i])

In [16]:
frame

[array(['BB McCullum (KKR)', '158', '-', '73', '10', '13', '216.43', 'KKR',
        'v RCB', 'Bengaluru', '18 Apr 2008', 'Twenty20'], dtype='<U24'),
 array(['MEK Hussey (CSK)', '116', '-', '54', '8', '9', '214.81',
        'Super Kings', 'v Kings XI', 'Mohali', '19 Apr 2008', 'Twenty20'],
       dtype='<U24'),
 array(['A Symonds (DC)', '117', '-', '53', '11', '7', '220.75',
        'Chargers', 'v Royals', 'Hyderabad', '24 Apr 2008', 'Twenty20'],
       dtype='<U24'),
 array(['AC Gilchrist (DC)', '109', '-', '47', '9', '10', '231.91',
        'Chargers', 'v Mumbai', 'DY Patil', '27 Apr 2008', 'Twenty20'],
       dtype='<U24'),
 array(['ST Jayasuriya (MI)', '114', '-', '48', '9', '11', '237.50',
        'Mumbai', 'v Super Kings', 'Wankhede', '14 May 2008', 'Twenty20'],
       dtype='<U24'),
 array(['SE Marsh (KXIP)', '115', '-', '69', '11', '7', '166.66',
        'Kings XI', 'v Royals', 'Mohali', '28 May 2008', 'Twenty20'],
       dtype='<U24'),
 array(['AB de Villiers (DC)', '105', '-', '54', '5', '6', '194.44',
        'Daredevils', 'v Super Kings', 'Durban', '23 Apr 2009', 'Twenty20'],
       dtype='<U24'),
 array(['MK Pandey (RCB)', '114', '-', '73', '10', '4', '156.16', 'RCB',
        'v Chargers', 'Centurion', '21 May 2009', 'Twenty20'], dtype='<U24'),
 array(['YK Pathan (RR)', '100', '-', '37', '9', '8', '270.27', 'Royals',
        'v Mumbai', 'Brabourne', '13 Mar 2010', 'Twenty20'], dtype='<U24'),
 array(['DA Warner (DC)', '107', '-', '69', '9', '5', '155.07',
        'Daredevils', 'v KKR', 'Delhi', '29 Mar 2010', 'Twenty20'],
       dtype='<U24'),
 array(['M Vijay (CSK)', '127', '-', '56', '8', '11', '226.78',
        'Super Kings', 'v Royals', 'Chennai', '03 Apr 2010', 'Twenty20'],
       dtype='<U24'),
 array(['DPMD Jayawardene (KXIP)', '110', '-', '59', '14', '3', '186.44',
        'Kings XI', 'v KKR', 'Eden Gardens', '04 Apr 2010', 'Twenty20'],
       dtype='<U24'),
 array(['PC Valthaty (KXIP)', '120', '-', '63', '19', '2', '190.47',
        'Kings XI', 'v Super Kings', 'Mohali', '13 Apr 2011', 'Twenty20'],
       dtype='<U24'),
 array(['SR Tendulkar (MI)', '100', '-', '66', '12', '3', '151.51',
        'Mumbai', 'v Kochi', 'Wankhede', '15 Apr 2011', 'Twenty20'],
       dtype='<U24'),
 array(['CH Gayle (RCB)', '102', '-', '55', '10', '7', '185.45', 'RCB',
        'v KKR', 'Eden Gardens', '22 Apr 2011', 'Twenty20'], dtype='<U24'),
 array(['V Sehwag (DC)', '119', '-', '56', '13', '6', '212.50',
        'Daredevils', 'v Chargers', 'Hyderabad', '05 May 2011', 'Twenty20'],
       dtype='<U24'),
 array(['CH Gayle (RCB)', '107', '68', '49', '10', '9', '218.36', 'RCB',
        'v Kings XI', 'Bengaluru', '06 May 2011', 'Twenty20'], dtype='<U24'),
 array(['AC Gilchrist (KXIP)', '106', '-', '55', '8', '9', '192.72',
        'Kings XI', 'v RCB', 'Dharamsala', '17 May 2011', 'Twenty20'],
       dtype='<U24'),
 array(['AM Rahane (RR)', '103', '86', '60', '12', '5', '171.66', 'Royals',
        'v RCB', 'Bengaluru', '15 Apr 2012', 'Twenty20'], dtype='<U24'),
 array(['KP Pietersen (DC)', '103', '92', '64', '6', '9', '160.93',
        'Daredevils', 'v Chargers', 'Delhi', '19 Apr 2012', 'Twenty20'],
       dtype='<U24'),
 array(['DA Warner (DC)', '109', '79', '54', '10', '7', '201.85',
        'Daredevils', 'v Chargers', 'Hyderabad', '10 May 2012', 'Twenty20'],
       dtype='<U24'),
 array(['RG Sharma (MI)', '109', '76', '60', '12', '5', '181.66', 'Mumbai',
        'v KKR', 'Eden Gardens', '12 May 2012', 'Twenty20'], dtype='<U24'),
 array(['CH Gayle (RCB)', '128', '95', '62', '7', '13', '206.45', 'RCB',
        'v Daredevils', 'Delhi', '17 May 2012', 'Twenty20'], dtype='<U24'),
 array(['M Vijay (CSK)', '113', '-', '58', '15', '4', '194.82',
        'Super Kings', 'v Daredevils', 'Chennai', '25 May 2012',
        'Twenty20'], dtype='<U24'),
 array(['SR Watson (RR)', '101', '82', '61', '6', '6', '165.57', 'Royals',
        'v Super Kings', 'Chennai', '22 Apr 2013', 'Twenty20'],
       dtype='<U24'),
 array(['CH Gayle (RCB)', '175', '102', '66', '13', '17', '265.15', 'RCB',
        'v Warriors', 'Bengaluru', '23 Apr 2013', 'Twenty20'], dtype='<U24'),
 array(['SK Raina (CSK)', '100', '82', '53', '7', '6', '188.67',
        'Super Kings', 'v Kings XI', 'Chennai', '02 May 2013', 'Twenty20'],
       dtype='<U24'),
 array(['DA Miller (KXIP)', '101', '54', '38', '8', '7', '265.78',
        'Kings XI', 'v RCB', 'Mohali', '06 May 2013', 'Twenty20'],
       dtype='<U24'),
 array(['LMP Simmons (MI)', '100', '86', '61', '14', '2', '163.93',
        'Mumbai', 'v Kings XI', 'Mohali', '21 May 2014', 'Twenty20'],
       dtype='<U24'),
 array(['V Sehwag (KXIP)', '122', '-', '58', '12', '8', '210.34',
        'Kings XI', 'v Super Kings', 'Wankhede', '30 May 2014', 'Twenty20'],
       dtype='<U24'),
 array(['WP Saha (KXIP)', '115', '66', '55', '10', '8', '209.09',
        'Kings XI', 'v KKR', 'Bengaluru', '01 Jun 2014', 'Twenty20'],
       dtype='<U24'),
 array(['BB McCullum (CSK)', '100', '97', '56', '7', '9', '178.57',
        'Super Kings', 'v Sunrisers', 'Chennai', '11 Apr 2015', 'Twenty20'],
       dtype='<U24'),
 array(['CH Gayle (RCB)', '117', '84', '57', '7', '12', '205.26', 'RCB',
        'v Kings XI', 'Bengaluru', '06 May 2015', 'Twenty20'], dtype='<U24'),
 array(['AB de Villiers (RCB)', '133', '82', '59', '19', '4', '225.42',
        'RCB', 'v Mumbai', 'Wankhede', '10 May 2015', 'Twenty20'],
       dtype='<U24'),
 array(['SR Watson (RR)', '104', '105', '59', '9', '5', '176.27', 'Royals',
        'v KKR', 'Brabourne', '16 May 2015', 'Twenty20'], dtype='<U24'),
 array(['Q de Kock (DC)', '108', '94', '51', '15', '3', '211.76',
        'Daredevils', 'v RCB', 'Bengaluru', '17 Apr 2016', 'Twenty20'],
       dtype='<U24'),
 array(['V Kohli (RCB)', '100', '88', '63', '11', '1', '158.73', 'RCB',
        'v Guj Lions', 'Rajkot', '24 Apr 2016', 'Twenty20'], dtype='<U24'),
 array(['SPD Smith (RPS)', '101', '77', '54', '8', '5', '187.03',
        'Supergiants', 'v Guj Lions', 'Pune', '29 Apr 2016', 'Twenty20'],
       dtype='<U24'),
 array(['V Kohli (RCB)', '108', '98', '58', '8', '7', '186.20', 'RCB',
        'v Supergiants', 'Bengaluru', '07 May 2016', 'Twenty20'],
       dtype='<U24'),
 array(['V Kohli (RCB)', '109', '94', '55', '5', '8', '198.18', 'RCB',
        'v Guj Lions', 'Bengaluru', '14 May 2016', 'Twenty20'],
       dtype='<U24'),
 array(['AB de Villiers (RCB)', '129', '78', '52', '10', '12', '248.07',
        'RCB', 'v Guj Lions', 'Bengaluru', '14 May 2016', 'Twenty20'],
       dtype='<U24'),
 array(['V Kohli (RCB)', '113', '-', '50', '12', '8', '226.00', 'RCB',
        'v Kings XI', 'Bengaluru', '18 May 2016', 'Twenty20'], dtype='<U24'),
 array(['SV Samson (DC)', '102', '82', '63', '8', '5', '161.90',
        'Daredevils', 'v Supergiant', 'Pune', '11 Apr 2017', 'Twenty20'],
       dtype='<U24'),
 array(['HM Amla (KXIP)', '104', '95', '60', '8', '6', '173.33',
        'Kings XI', 'v Mumbai', 'Indore', '20 Apr 2017', 'Twenty20'],
       dtype='<U24'),
 array(['DA Warner (SRH)', '126', '80', '59', '10', '8', '213.55',
        'Sunrisers', 'v KKR', 'Hyderabad', '30 Apr 2017', 'Twenty20'],
       dtype='<U24'),
 array(['BA Stokes (RPS)', '103', '85', '63', '7', '6', '163.49',
        'Supergiant', 'v Guj Lions', 'Pune', '01 May 2017', 'Twenty20'],
       dtype='<U24'),
 array(['HM Amla (KXIP)', '104', '90', '60', '8', '5', '173.33',
        'Kings XI', 'v Guj Lions', 'Mohali', '07 May 2017', 'Twenty20'],
       dtype='<U24'),
 array(['CH Gayle (KXIP)', '104', '-', '63', '1', '11', '165.07',
        'Kings XI', 'v Sunrisers', 'Mohali', '19 Apr 2018', 'Twenty20'],
       dtype='<U24'),
 array(['SR Watson (CSK)', '106', '-', '57', '9', '6', '185.96',
        'Super Kings', 'v Royals', 'Pune', '20 Apr 2018', 'Twenty20'],
       dtype='<U24'),
 array(['RR Pant (DC)', '128', '-', '63', '15', '7', '203.17',
        'Daredevils', 'v Sunrisers', 'Delhi', '10 May 2018', 'Twenty20'],
       dtype='<U24'),
 array(['AT Rayudu (CSK)', '100', '-', '62', '7', '7', '161.29',
        'Super Kings', 'v Sunrisers', 'Pune', '13 May 2018', 'Twenty20'],
       dtype='<U24'),
 array(['SR Watson (CSK)', '117', '-', '57', '11', '8', '205.26',
        'Super Kings', 'v Sunrisers', 'Wankhede', '27 May 2018',
        'Twenty20'], dtype='<U24'),
 array(['SV Samson (RR)', '102', '85', '55', '10', '4', '185.45', 'Royals',
        'v Sunrisers', 'Hyderabad', '29 Mar 2019', 'Twenty20'],
       dtype='<U24'),
 array(['JM Bairstow (SRH)', '114', '76', '56', '12', '7', '203.57',
        'Sunrisers', 'v RCB', 'Hyderabad', '31 Mar 2019', 'Twenty20'],
       dtype='<U24'),
 array(['DA Warner (SRH)', '100', '98', '55', '5', '5', '181.81',
        'Sunrisers', 'v RCB', 'Hyderabad', '31 Mar 2019', 'Twenty20'],
       dtype='<U24'),
 array(['KL Rahul (KXIP)', '100', '110', '64', '6', '6', '156.25',
        'Kings XI', 'v Mumbai', 'Wankhede', '10 Apr 2019', 'Twenty20'],
       dtype='<U24'),
 array(['V Kohli (RCB)', '100', '98', '58', '9', '4', '172.41', 'RCB',
        'v KKR', 'Eden Gardens', '19 Apr 2019', 'Twenty20'], dtype='<U24'),
 array(['AM Rahane (RR)', '105', '100', '63', '11', '3', '166.66',
        'Royals', 'v Capitals', 'Jaipur', '22 Apr 2019', 'Twenty20'],
       dtype='<U24'),
 array(['KL Rahul (KXIP)', '132', '-', '69', '14', '7', '191.30',
        'Kings XI', 'v RCB', 'Dubai (DSC)', '24 Sep 2020', 'Twenty20'],
       dtype='<U24'),
 array(['MA Agarwal (KXIP)', '106', '-', '50', '10', '7', '212.00',
        'Kings XI', 'v Royals', 'Sharjah', '27 Sep 2020', 'Twenty20'],
       dtype='<U24'),
 array(['S Dhawan (DC)', '101', '-', '58', '14', '1', '174.13', 'Capitals',
        'v Super Kings', 'Sharjah', '17 Oct 2020', 'Twenty20'],
       dtype='<U24'),
 array(['S Dhawan (DC)', '106', '-', '61', '12', '3', '173.77', 'Capitals',
        'v Kings XI', 'Dubai (DSC)', '20 Oct 2020', 'Twenty20'],
       dtype='<U24'),
 array(['BA Stokes (RR)', '107', '-', '60', '14', '3', '178.33', 'Royals',
        'v Mumbai', 'Abu Dhabi', '25 Oct 2020', 'Twenty20'], dtype='<U24'),
 array(['SV Samson (RR)', '119', '112', '63', '12', '7', '188.88',
        'Royals', 'v Punjab Kings', 'Wankhede', '12 Apr 2021', 'Twenty20'],
       dtype='<U24'),
 array(['D Padikkal (RCB)', '101', '74', '52', '11', '6', '194.23', 'RCB',
        'v Royals', 'Wankhede', '22 Apr 2021', 'Twenty20'], dtype='<U24'),
 array(['JC Buttler (RR)', '124', '95', '64', '11', '8', '193.75',
        'Royals', 'v Sunrisers', 'Delhi', '02 May 2021', 'Twenty20'],
       dtype='<U24'),
 array(['RD Gaikwad (CSK)', '101', '113', '60', '9', '5', '168.33',
        'Super Kings', 'v Royals', 'Abu Dhabi', '02 Oct 2021', 'Twenty20'],
       dtype='<U24'),
 array(['JC Buttler (RR)', '100', '97', '68', '11', '5', '147.05',
        'Royals', 'v Mumbai', 'DY Patil', '02 Apr 2022', 'Twenty20'],
       dtype='<U24'),
 array(['KL Rahul (LSG)', '103', '103', '60', '9', '5', '171.66',
        'Super Giants', 'v Mumbai', 'Brabourne', '16 Apr 2022', 'Twenty20'],
       dtype='<U24'),
 array(['JC Buttler (RR)', '103', '93', '61', '9', '5', '168.85', 'Royals',
        'v KKR', 'Brabourne', '18 Apr 2022', 'Twenty20'], dtype='<U24'),
 array(['JC Buttler (RR)', '116', '103', '65', '9', '9', '178.46',
        'Royals', 'v Capitals', 'Wankhede', '22 Apr 2022', 'Twenty20'],
       dtype='<U24'),
 array(['KL Rahul (LSG)', '103', '106', '62', '12', '4', '166.12',
        'Super Giants', 'v Mumbai', 'Wankhede', '24 Apr 2022', 'Twenty20'],
       dtype='<U24'),
 array(['Q de Kock (LSG)', '140', '97', '70', '10', '10', '200.00',
        'Super Giants', 'v KKR', 'DY Patil', '18 May 2022', 'Twenty20'],
       dtype='<U24'),
 array(['RM Patidar (RCB)', '112', '100', '54', '12', '7', '207.40', 'RCB',
        'v Super Giants', 'Eden Gardens', '25 May 2022', 'Twenty20'],
       dtype='<U24'),
 array(['JC Buttler (RR)', '106', '86', '60', '10', '6', '176.66',
        'Royals', 'v RCB', 'Ahmedabad', '27 May 2022', 'Twenty20'],
       dtype='<U24'),
 array(['HC Brook (SRH)', '100', '99', '55', '12', '3', '181.81',
        'Sunrisers', 'v KKR', 'Eden Gardens', '14 Apr 2023', 'Twenty20'],
       dtype='<U24'),
 array(['VR Iyer (KKR)', '104', '82', '51', '6', '9', '203.92', 'KKR',
        'v Mumbai', 'Wankhede', '16 Apr 2023', 'Twenty20'], dtype='<U24'),
 array(['YBK Jaiswal (RR)', '124', '112', '62', '16', '8', '200.00',
        'Royals', 'v Mumbai', 'Wankhede', '30 Apr 2023', 'Twenty20'],
       dtype='<U24'),
 array(['SA Yadav (MI)', '103', '73', '49', '11', '6', '210.20', 'Mumbai',
        'v Titans', 'Wankhede', '12 May 2023', 'Twenty20'], dtype='<U24'),
 array(['Prabhsimran Singh (PBKS)', '103', '87', '65', '10', '6', '158.46',
        'Punjab Kings', 'v Capitals', 'Delhi', '13 May 2023', 'Twenty20'],
       dtype='<U24'),
 array(['Shubman Gill (GT)', '101', '100', '58', '13', '1', '174.13',
        'Titans', 'v Sunrisers', 'Ahmedabad', '15 May 2023', 'Twenty20'],
       dtype='<U24'),
 array(['H Klaasen (SRH)', '104', '62', '51', '8', '6', '203.92',
        'Sunrisers', 'v RCB', 'Hyderabad', '18 May 2023', 'Twenty20'],
       dtype='<U24'),
 array(['V Kohli (RCB)', '100', '82', '63', '12', '4', '158.73', 'RCB',
        'v Sunrisers', 'Hyderabad', '18 May 2023', 'Twenty20'],
       dtype='<U24'),
 array(['C Green (MI)', '100', '85', '47', '8', '8', '212.76', 'Mumbai',
        'v Sunrisers', 'Wankhede', '21 May 2023', 'Twenty20'], dtype='<U24'),
 array(['V Kohli (RCB)', '101', '102', '61', '13', '1', '165.57', 'RCB',
        'v Titans', 'Bengaluru', '21 May 2023', 'Twenty20'], dtype='<U24'),
 array(['Shubman Gill (GT)', '104', '97', '52', '5', '8', '200.00',
        'Titans', 'v RCB', 'Bengaluru', '21 May 2023', 'Twenty20'],
       dtype='<U24')]

In [48]:
raw_data = pd.DataFrame(frame,columns=columns)

Records in Indian Premier League

List of hundreds till 2023

In [49]:
raw_data.head()

,Player,Runs,Mins,Balls,4s,6s,SR,Team,Opposition,Ground,Match Date,Scorecard
0,BB McCullum (KKR),158,-,73,10,13,216.43,KKR,v RCB,Bengaluru,18 Apr 2008,Twenty20
1,MEK Hussey (CSK),116,-,54,8,9,214.81,Super Kings,v Kings XI,Mohali,19 Apr 2008,Twenty20
2,A Symonds (DC),117,-,53,11,7,220.75,Chargers,v Royals,Hyderabad,24 Apr 2008,Twenty20
3,AC Gilchrist (DC),109,-,47,9,10,231.91,Chargers,v Mumbai,DY Patil,27 Apr 2008,Twenty20
4,ST Jayasuriya (MI),114,-,48,9,11,237.50,Mumbai,v Super Kings,Wankhede,14 May 2008,Twenty20

In [37]:
raw_data.dtypes

Player        object
Runs          object
Mins          object
Balls         object
4s            object
6s            object
SR            object
Team          object
Opposition    object
Ground        object
Match Date    object
Scorecard     object
dtype: object

In [51]:
raw_data['Mins'] = raw_data['Mins'].apply(lambda x: np.NaN if x == '-' else x)

In [52]:
raw_data

,Player,Runs,Mins,Balls,4s,6s,SR,Team,Opposition,Ground,Match Date,Scorecard
0,BB McCullum (KKR),158,NaN,73,10,13,216.43,KKR,v RCB,Bengaluru,18 Apr 2008,Twenty20
1,MEK Hussey (CSK),116,NaN,54,8,9,214.81,Super Kings,v Kings XI,Mohali,19 Apr 2008,Twenty20
2,A Symonds (DC),117,NaN,53,11,7,220.75,Chargers,v Royals,Hyderabad,24 Apr 2008,Twenty20
3,AC Gilchrist (DC),109,NaN,47,9,10,231.91,Chargers,v Mumbai,DY Patil,27 Apr 2008,Twenty20
4,ST Jayasuriya (MI),114,NaN,48,9,11,237.50,Mumbai,v Super Kings,Wankhede,14 May 2008,Twenty20
...,...,...,...,...,...,...,...,...,...,...,...,...
81,H Klaasen (SRH),104,62,51,8,6,203.92,Sunrisers,v RCB,Hyderabad,18 May 2023,Twenty20
82,V Kohli (RCB),100,82,63,12,4,158.73,RCB,v Sunrisers,Hyderabad,18 May 2023,Twenty20
83,C Green (MI),100,85,47,8,8,212.76,Mumbai,v Sunrisers,Wankhede,21 May 2023,Twenty20
84,V Kohli (RCB),101,102,61,13,1,165.57,RCB,v Titans,Bengaluru,21 May 2023,Twenty20
85,Shubman Gill (GT),104,97,52,5,8,200.00,Titans,v RCB,Bengaluru,21 May 2023,Twenty20

In [59]:
raw_data = raw_data.astype({
    "Runs":"int", "Mins":"float" ,"Balls":"float", "4s":"float" ,"6s":"float", "SR":"float"
})

In [60]:
raw_data.dtypes

Player         object
Runs            int32
Mins          float64
Balls         float64
4s            float64
6s            float64
SR            float64
Team           object
Opposition     object
Ground         object
Match Date     object
Scorecard      object
dtype: object

In [65]:
raw_data["Match Date"] = pd.to_datetime(df["Match Date"].str.strip(),format = "%d %b %Y")

In [67]:
raw_data.dtypes

Player                object
Runs                   int32
Mins                 float64
Balls                float64
4s                   float64
6s                   float64
SR                   float64
Team                  object
Opposition            object
Ground                object
Match Date    datetime64[ns]
Scorecard             object
dtype: object

In [68]:
raw_data.head(20)

,Player,Runs,Mins,Balls,4s,6s,SR,Team,Opposition,Ground,Match Date,Scorecard
0,BB McCullum (KKR),158,NaN,73.0,10.0,13.0,216.43,KKR,v RCB,Bengaluru,2008-04-18,Twenty20
1,MEK Hussey (CSK),116,NaN,54.0,8.0,9.0,214.81,Super Kings,v Kings XI,Mohali,2008-04-19,Twenty20
2,A Symonds (DC),117,NaN,53.0,11.0,7.0,220.75,Chargers,v Royals,Hyderabad,2008-04-24,Twenty20
3,AC Gilchrist (DC),109,NaN,47.0,9.0,10.0,231.91,Chargers,v Mumbai,DY Patil,2008-04-27,Twenty20
4,ST Jayasuriya (MI),114,NaN,48.0,9.0,11.0,237.50,Mumbai,v Super Kings,Wankhede,2008-05-14,Twenty20
5,SE Marsh (KXIP),115,NaN,69.0,11.0,7.0,166.66,Kings XI,v Royals,Mohali,2008-05-28,Twenty20
6,AB de Villiers (DC),105,NaN,54.0,5.0,6.0,194.44,Daredevils,v Super Kings,Durban,2009-04-23,Twenty20
7,MK Pandey (RCB),114,NaN,73.0,10.0,4.0,156.16,RCB,v Chargers,Centurion,2009-05-21,Twenty20
8,YK Pathan (RR),100,NaN,37.0,9.0,8.0,270.27,Royals,v Mumbai,Brabourne,2010-03-13,Twenty20
9,DA Warner (DC),107,NaN,69.0,9.0,5.0,155.07,Daredevils,v KKR,Delhi,2010-03-29,Twenty20
10,M Vijay (CSK),127,NaN,56.0,8.0,11.0,226.78,Super Kings,v Royals,Chennai,2010-04-03,Twenty20
11,DPMD Jayawardene (KXIP),110,NaN,59.0,14.0,3.0,186.44,Kings XI,v KKR,Eden Gardens,2010-04-04,Twenty20
12,PC Valthaty (KXIP),120,NaN,63.0,19.0,2.0,190.47,Kings XI,v Super Kings,Mohali,2011-04-13,Twenty20
13,SR Tendulkar (MI),100,NaN,66.0,12.0,3.0,151.51,Mumbai,v Kochi,Wankhede,2011-04-15,Twenty20
14,CH Gayle (RCB),102,NaN,55.0,10.0,7.0,185.45,RCB,v KKR,Eden Gardens,2011-04-22,Twenty20
15,V Sehwag (DC),119,NaN,56.0,13.0,6.0,212.50,Daredevils,v Chargers,Hyderabad,2011-05-05,Twenty20
16,CH Gayle (RCB),107,68.0,49.0,10.0,9.0,218.36,RCB,v Kings XI,Bengaluru,2011-05-06,Twenty20
17,AC Gilchrist (KXIP),106,NaN,55.0,8.0,9.0,192.72,Kings XI,v RCB,Dharamsala,2011-05-17,Twenty20
18,AM Rahane (RR),103,86.0,60.0,12.0,5.0,171.66,Royals,v RCB,Bengaluru,2012-04-15,Twenty20
19,KP Pietersen (DC),103,92.0,64.0,6.0,9.0,160.93,Daredevils,v Chargers,Delhi,2012-04-19,Twenty20

In [70]:
raw_data.to_csv("cricket_data.csv",index=False)